AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::Serverless-2016-10-31]
Description: CloudFormation template to create PostgreSQL RDS instance.

Parameters:
  DBInstanceIdentifier:
    Description: "Identifier for the RDS instance"
    Type: String

  DBInstanceClass:
    Description: "The instance class for the PostgreSQL RDS instance"
    Type: String
    Default: db.t3.micro

  Engine:
    Description: "The database engine to use"
    Type: String
    Default: postgres
    AllowedValues: 
      - postgres

  AllocatedStorage:
    Description: "The allocated storage size (in GB) for the RDS instance"
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 1000

  DBName:
    Description: "Name of the initial database to create"
    Type: String

  BackupRetentionPeriod:
    Description: "The number of days to retain backups"
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35

  VPCId:
    Description: "The VPC ID where the RDS instance will be deployed"
    Type: AWS::EC2::VPC::Id

  AllowedCIDR:
    Description: "The allowed CIDR range for inbound PostgreSQL traffic"
    Type: String
    Default: 0.0.0.0/0
    ConstraintDescription: "Must be a valid CIDR range."

  PubliclyAccessible:
    Description: "Indicates whether the RDS instance is publicly accessible"
    Type: String
    Default: false
    AllowedValues: 
      - true
      - false

  MultiAZ:
    Description: "Specifies if the RDS instance is Multi-AZ"
    Type: String
    Default: false
    AllowedValues: 
      - true
      - false

  StorageType:
    Description: "The storage type for the RDS instance"
    Type: String
    Default: gp2
    ConstraintDescription: "Must be a valid RDS storage type."
    AllowedValues: 
      - gp2
      - io1

Resources:
  # Create a Security Group for the RDS instance
  MiraRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for PostgreSQL RDS instance"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref AllowedCIDR
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 0
          CidrIp: "0.0.0.0/0"

  # Store the username in SSM Parameter Store
  MiraDBUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/rds/${DBInstanceIdentifier}/username"
      Type: String
      Value: !Ref DBUsername
      Tier: Standard

  # Store the password in SSM Parameter Store (SecureString)
  MiraDBPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/rds/${DBInstanceIdentifier}/password"
      Type: SecureString
      Value: !Ref DBPassword
      Tier: Standard
      Description: Password for the RDS instance
      KeyId: alias/aws/ssm # Uses default KMS key

  # Create a PostgreSQL RDS instance with SSM Parameters
  MiraRDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: 
      - MiraDBUsernameParameter
      - MiraDBPasswordParameter
    Properties: 
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      AllocatedStorage: !Ref AllocatedStorage
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      VPCSecurityGroups:
        - !GetAtt MiraRDSSecurityGroup.GroupId
      PubliclyAccessible: !Ref PubliclyAccessible
      MultiAZ: !Ref MultiAZ
      StorageType: !Ref StorageType
      DeletionPolicy: Snapshot

Outputs:
  # Output the endpoint of the RDS instance
  MiraRDSEndpoint:
    Description: "The endpoint of the PostgreSQL RDS instance"
    Value: !GetAtt MiraRDSInstance.Endpoint.Address
    Export:
      Name: MiraRDSInstanceEndpoint
