AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for Feature Flag JSON File

Parameters:
  # Parameters Docs:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
  Environment:
    Description: The environment name (e.g., prod, dev, staging, gh ref, your user name).
    Type: String
    Default: dev
    MaxLength: "60"  # Prevents the 64 for char limit for OriginAccessControlConfig.Name
  S3Bucket:
    Description: S3 bucket name for storing feature_flag.json file
    Type: String
    Default: dev
    MaxLength: "60"

Conditions:
  IsTestingStagingProduction: !Or [
      # Use OR to check for any of the values
      !Equals [!Ref Environment, "Testing"],
      !Equals [!Ref Environment, "Staging"],
      !Equals [!Ref Environment, "Production"],
    ]

Resources:
  S3BucketWithVersioning:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3Bucket
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: "S3 bucket Name of Feature Flag JSON File"
    Value: !Ref S3BucketWithVersioning
    Export:
      Name: !Sub "S3BucketName-${Environment}"

  BucketArn:
    Description: "S3 bucket ARN of Feature Flag JSON File"
    Value: !GetAtt S3BucketWithVersioning.Arn
    Export:
      Name: !Sub "S3BucketArn-${Environment}"
