name: api-stage-codedeploy

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "This commit_hash we will use to rollback the codedeploy"
        required: false
      codedeploy_rollback:
        description: "This commit_hash we will use to rollback the codedeploy"
        required: true
        default: 'false'
  push:
    branches:
      - multi_tenant_stage

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  api_codedeploy:
    name: Trigger codedeploy of API to Stage
    runs-on: ubuntu-latest

    environment:
      name: STAGE

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Echo Branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "branch name is : $branch_name"
          echo "ENV name is : ${{ vars.ENV }}"

          if [ -z "${{ github.event.inputs.commit_hash }}" ]; then
            commit_hash=$(git rev-parse HEAD)
          else
            commit_hash=${{ github.event.inputs.commit_hash }}
          fi

          echo "commit_hash=$commit_hash"

  release-dependent-codedeploy:
    name: "Release Dependent Codedeploy"
    needs: api_codedeploy
    runs-on: ubuntu-latest
    steps:
      - name: Capture codedeploy_rollback
        run: echo "codedeploy_rollback=${{ inputs.codedeploy_rollback }}" >> $GITHUB_ENV

      - name: Use codedeploy_rollback input
        run: echo "Rollback input is ${{ inputs.codedeploy_rollback }}"

      - name: Trigger release-dependent-codedeploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run release-dependent-codedeploy.yml \
          --repo prashant-cloudbolt/api \
          --field codedeploy_rollback=${{ env.codedeploy_rollback }}

      - name: Get Workflow Run ID of release-dependent-codedeploy.yml workflow
        id: get_run_id
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          max_attempts=5  # Maximum number of attempts to retrieve the workflow run ID
          attempt=0
          workflow_list=""

          while [ -z "$workflow_list" ] && [ $attempt -lt $max_attempts ]; do
            echo "Attempt $(($attempt+1)) to retrieve workflow run ID"
            workflow_list=$(gh run list --repo prashant-cloudbolt/api --workflow=release-dependent-codedeploy.yml --limit=1 --json databaseId)
            
            if [ -z "$workflow_list" ]; then
              echo "Workflow run ID not yet available. Retrying..."
              attempt=$(($attempt + 1))
              sleep 10  # Wait for a short time before retrying
            else
              echo "Workflow run ID retrieved successfully."
            fi
          done

          if [ -z "$workflow_list" ]; then
            echo "Failed to retrieve workflow run ID after $max_attempts attempts"
            exit 1
          fi

          run_id=$(echo "$workflow_list" | jq -r '.[0].databaseId')
          echo "run_id=$run_id" >> $GITHUB_ENV

      - name: Echo Run_ID
        run: echo "Run ID= ${{ env.run_id }}"

      - name: Watch workflow run of release-dependent-codedeploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh run watch ${{ env.run_id }}

      - name: Notify failure to Slack
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() }} # This ensures the step runs only if the previous steps fail
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }} 
        with:
          status: ${{ job.status }}
          message: |
            :rotating_light: *Urgent*: Release Dependent CodeDeploy Workflow Failed for API of CSMP-Stage Environment:rotating_light:
            Repository: ${{ github.repository }}
            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}