name: api-stage-codedeploy

on:
  workflow_call:
    inputs:
      codedeploy_rollback:
        description: "Trigger rollback in dependent workflow if value is True"
        required: false
        type: string

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  codedeploy:
    runs-on: ubuntu-latest

    environment:
      name: STAGE

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Print inputs
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "branch name is : $branch_name"
          echo "ENV name is : ${{ vars.ENV }}"
          echo "Codedeploy rollback  is : ${{ inputs.codedeploy_rollback }}"

      - name: Get Commit Hash from Tag
        if: ${{ inputs.codedeploy_rollback == 'True' }}
        id: commit_hash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          case $branch_name in
            multi_tenant_*)
              branch_suffix=$(echo "$branch_name" | sed 's/multi_tenant_//; s/-//g')
              ;;
            mira-stage)
              branch_suffix="STAGE"
              ;;
            *)
              echo "Unsupported branch: $branch_name"
              exit 1
              ;;
          esac

          # Convert suffix to uppercase
          branch_suffix=$(tr '[:lower:]' '[:upper:]' <<< "$branch_suffix")
          echo "branch_suffix=$branch_suffix" >> $GITHUB_ENV

          latest_release=$(gh release list --limit 30 | grep -E "$branch_suffix" | sort -k4 -r | head -n 1 | awk '{print $1}')
          echo "latest_release=$latest_release" >> $GITHUB_ENV

          release_tag=$(gh release view $latest_release --json tagName -q ".tagName")
          echo "release_tag=$release_tag" >> $GITHUB_ENV

          commit_hash=$(gh api repos/${{ github.repository }}/git/ref/tags/$release_tag --jq '.object.sha')
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Display Results of Release, Tag, Hash
        if: ${{ inputs.codedeploy_rollback == 'True' }}
        run: |
          echo "Branch Suffix: ${{ env.branch_suffix }}"
          echo "Current Release: ${{ env.latest_release }}"
          echo "Current Release Tag: ${{ env.release_tag }}"
          echo "Commit Hash of Tag: ${{ env.commit_hash }}"

      - name: echo git hash
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "branch name is : $branch_name"
          echo "ENV name is : ${{ vars.ENV }}"

          if [ -z "${{ env.commit_hash }}" ]; then
            commit_hash=$(git rev-parse HEAD)
          else
            commit_hash=${{ env.commit_hash }}
          fi

          echo "commit_hash=$commit_hash"

  release-dependent-codedeploy:
    name: "Release Dependent Codedeploy"
    needs: codedeploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Print inputs
        run: |
          echo "Codedeploy rollback  is : ${{ inputs.codedeploy_rollback }}"

      - name: Run release-dependent-codedeploy.yml workflow
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: multi_tenant_stage
          repo: api
          owner: prashant-cloudbolt
          workflow: release-dependent-codedeploy.yml
          workflow_inputs: '{ "codedeploy_rollback": "${{ inputs.codedeploy_rollback }}",  "environment": "CSMP_Stage" }'

      - name: Watch release-dependent-codedeploy.yml workflow
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RUN_ID=${{ steps.return_dispatch.outputs.run_id }}
          gh run watch $RUN_ID --repo prashant-cloudbolt/api

      - name: Notify failure to Slack
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() }} # This ensures the step runs only if the previous steps fail
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }} 
        with:
          status: ${{ job.status }}
          message: |
            :rotating_light: *Urgent*: Release Dependent CodeDeploy Workflow Failed for API of CSMP-Stage Environment:rotating_light:
            Repository: ${{ github.repository }}
            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}