name: api-mirastage-codedeploy

on:
  workflow_call:

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  codedeploy:
    name: Trigger codedeploy with latest commit to MIRA Stage
    runs-on: ubuntu-latest

    environment:
      name: MIRA-STAGE

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          ref: multi_tenant_stage

      - name: Echo Branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo $branch_name
          echo "ENV name is : ${{ vars.ENV }}"

      - name: Pause ASG termination process
        id: pause_asg
        run: |
          echo "pause ASG"
          exit 0

      - name: Trigger CodeDeploy Deployment for Node API
        run: |
          exit 1

      - name: Resume ASG termination process
        if: always() && steps.pause_asg.conclusion == 'success'
        env:
          APPLICATION_NAME: ${{ vars.CODEDEPLOY_APPLICATION }}
        run: |
          echo "Aways run even if Trigger CodeDeploy Deployment for Node API fail"