name: Deploy Dev Environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  s3-feature-flag:
    name: S3 Feature Flag Json File
    uses: ./.github/workflows/s3-feature-flag.yml
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    secrets: inherit
    with:
        environment: "Development"
        stack-name: "test-stack"
        working-directory: "."