name: Deploy

on:
  push:
    branches:
      - "multi_tenant_stage"

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy-testing:
    name: Deploy to Mira Testing Environment
    if: github.ref_name == 'multi_tenant_stage'
    runs-on: ubuntu-latest

    environment:
      name: Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_KEY }}
          aws-region: us-east-1

      - name: Create S3 bucket and upload feature flag
        continue-on-error: true
        uses: ./.github/actions/s3-feature-flag
        with:
          environment: "testing"
          feature-flag-s3-bucket: ${{ vars.FEATURE_FLAG_S3_BUCKET }}
          feature-flag-file-name: ${{ vars.FEATURE_FLAG_FILE_NAME }}
          working-directory: "."

  trigger-deployment-to-staging:
    name: Trigger Deployment to Mira Staging
    if: github.ref_name == 'multi_tenant_stage'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run deploy.yml --repo prashant-cloudbolt/node-api --field "environment=Staging"