name: Deploy Dev Environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy-dev:
    name: Deploy to Mira Development Environment
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get modified files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > modified_files.txt
          echo "Modified files:"
          cat modified_files.txt

      - name: Check if services/feature_flag/staging/feature_flag.json is modified
        run: |
          if grep -q "services/feature_flag/staging/feature_flag.json" modified_files.txt; then
            echo "services/feature_flag/staging/feature_flag.json has been modified."
            echo "file_modified=true" >> $GITHUB_ENV
          else
            echo "services/feature_flag/staging/feature_flag.json has NOT been modified."
            echo "file_modified=false" >> $GITHUB_ENV
          fi

      - name: Conditional step based on file modification
        if: env.file_modified == 'true'
        run: |
          echo "Performing actions because services/feature_flag/staging/feature_flag.json is modified."

      # - name: Create S3 bucket and upload feature flag
      #   # continue-on-error: true
      #   uses: ./.github/actions/s3-feature-flag
      #   with:
      #     environment: "Development"
      #     region: ${{ vars.AWS_REGION }}
      #     feature-flag-s3-bucket: ${{ vars.FEATURE_FLAG_S3_BUCKET }}
      #     feature-flag-file-name: ${{ vars.FEATURE_FLAG_FILE_NAME }}
      #     working-directory: "."
      #