name: Deploy Dev Environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy-dev:
    name: Deploy to Mira Development Environment
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create S3 bucket and upload feature flag
        continue-on-error: true  # Allows the workflow to proceed even if this step fails
        uses: ./.github/actions/s3-feature-flag
        with:
          environment: "development"
          region: ${{ vars.AWS_REGION }}
          feature-flag-s3-bucket: ${{ vars.FEATURE_FLAG_S3_BUCKET }}
          feature-flag-file-name: ${{ vars.FEATURE_FLAG_FILE_NAME }}
          working-directory: "."

      - name: Deploy CloudFormation Stack of postgreSQL RDS Instance
        run: |
          aws cloudformation deploy \
            --stack-name mira-development-postgressql-instance \
            --template-file postgres.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              DBInstanceIdentifier=postgres-instance \
              DBUsername="${{ secrets.MIRA_POSTGRES_USERNAME }}" \
              DBPassword="${{ secrets.MIRA_POSTGRES_PASSWORD }}" \
              DBName=development \
              VPCId=vpc-0cd8a0084b79bf7f8 \
              AllocatedStorage=20 \
              PubliclyAccessible=true \
              MultiAZ=false