# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    id: reusable

  use-output:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Use output from reusable workflow
        run: echo "Output from reusable workflow: ${{ needs.call-reusable-workflow.outputs.example_output }}"
