name: qa-automation

on:
  workflow_call:
    outputs:
      job_status:
        description: "QA Automation job status"
        value: ${{ jobs.qa_jobs_status.outputs.job_status }}

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  qa_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workflow_name:
          - csmp_stage_V2_api_test.yml
          - csmp_stage_smoke_test.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ${{ matrix.workflow_name }} workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run ${{ matrix.workflow_name }} --repo prashant-cloudbolt/qa-automation
          echo "Waiting 10 seconds before checking for workflow run ID..."
          sleep 10

      - name: Get Workflow Run ID of ${{ matrix.workflow_name }}
        id: get_run_id
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          max_attempts=10
          attempt=0
          workflow_list=""

          while [ -z "$workflow_list" ] && [ $attempt -lt $max_attempts ]; do
            echo "Attempt $((attempt + 1)) to retrieve workflow run ID"
            workflow_list=$(gh run list --repo prashant-cloudbolt/qa-automation --workflow=${{ matrix.workflow_name }} --limit=1 --json databaseId)
            
            if [ -z "$workflow_list" ]; then
              echo "Workflow run ID not yet available. Retrying..."
              attempt=$((attempt + 1))
              sleep 10
            else
              echo "Workflow run ID retrieved successfully."
            fi
          done

          if [ -z "$workflow_list" ]; then
            echo "Failed to retrieve workflow run ID after $max_attempts attempts"
            exit 1
          fi

          run_id=$(echo "$workflow_list" | jq -r '.[0].databaseId')
          echo "Run ID of ${{ matrix.workflow_name }} : $run_id"
          echo "run_id=$run_id" >> $GITHUB_ENV

      - name: Check Status of ${{ matrix.workflow_name }}
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          status=""
          while [ "$status" != "completed" ]; do
            status=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json status --jq '.status')
            echo "Current status: $status"
            if [ "$status" == "completed" ]; then
              conclusion=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json conclusion --jq '.conclusion')
              echo "Final conclusion: $conclusion"
              if [ "$conclusion" != "success" ]; then
                echo "status=failure"
                exit 1
              else
                echo "status=success"
              fi
            fi
            sleep 15
          done

  qa_jobs_status:
    needs: [qa_tests]
    runs-on: ubuntu-latest
    if: always()
    outputs:
      job_status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Set final job status
        id: set_status
        run: |
          if [ "${{ needs.qa_tests.result }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - name: Notify Failure to Slack
        if: ${{ steps.set_status.outputs.status == 'failure' }}
        uses: act10ns/slack@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
        with:
          status: failure
          message: |
            :rotating_light: *QA Automation Failed* :rotating_light:

            The following tests failed:
            ${{ contains(needs.qa_tests.outputs.job_status, 'failure') && ':x: Stage CSMP V2 API Test Job' || ':white_check_mark: Stage CSMP V2 API Test Job' }}
            ${{ contains(needs.qa_tests.outputs.job_status, 'failure') && ':x: CSMP Stage Smoke Test Runner' || ':white_check_mark: CSMP Stage Smoke Test Runner' }}

            :warning: *Automatic rollback to the previous version has been initiated!* :warning:

            Repository: ${{ github.repository }}
            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}