name: qa-automation

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK:
        required: true

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  qa-tests:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run maven.yml workflow in qa-automation repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run maven.yml --repo prashant-cloudbolt/qa-automation

      - name: Get Workflow Run ID of maven.yml workflow
        id: get_run_id
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          max_attempts=5  # Maximum number of attempts to retrieve the workflow run ID
          attempt=0
          workflow_list=""

          while [ -z "$workflow_list" ] && [ $attempt -lt $max_attempts ]; do
            echo "Attempt $(($attempt+1)) to retrieve workflow run ID"
            workflow_list=$(gh run list --repo prashant-cloudbolt/qa-automation --workflow=maven.yml --branch=multi_tenant_stage --limit=1 --json databaseId)
            
            if [ -z "$workflow_list" ]; then
              echo "Workflow run ID not yet available. Retrying..."
              attempt=$(($attempt + 1))
              sleep 10  # Wait for a short time before retrying
            else
              echo "Workflow run ID retrieved successfully."
            fi
          done

          if [ -z "$workflow_list" ]; then
            echo "Failed to retrieve workflow run ID after $max_attempts attempts"
            exit 1
          fi

          run_id=$(echo "$workflow_list" | jq -r '.[0].databaseId')
          echo "run_id=$run_id" >> $GITHUB_ENV


      - name: Check Target Workflow Status of maven.yml
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true  # Continue even if the command fails, so output is set correctly
        run: |
          status=""
          while [ "$status" != "completed" ]; do
            status=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json status --jq '.status')
            echo "Current status: $status"
            if [ "$status" == "completed" ]; then
              conclusion=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json conclusion --jq '.conclusion')
              echo "Final conclusion: $conclusion"
              if [ "$conclusion" != "success" ]; then
                echo "Target workflow failed. Failing source workflow."
                echo "status=failure" >> $GITHUB_OUTPUT
                exit 1
              else
                echo "status=success" >> $GITHUB_OUTPUT
              fi
            fi
            sleep 15  # Increased sleep to reduce API calls
          done

      - name: Debug Status Output
        run: |
          echo "Set status to: ${{ steps.check_status.outputs.status }}"

      - name: Notify failure to Slack
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
        with:
          status: ${{ job.status }}
          message: |
            :rotating_light: *QA Tests Failed*: API Deployment for CSMP-STAGE Environment
            Repository: ${{ github.repository }}
            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  # codedeploy_rollback:
  #   if: ${{ always() && needs.qa-tests.result == 'failure' }} # Runs if `qa-tests` fails
  #   needs: qa-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Get Commit Hash from Tag
  #       id: commit_hash
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #       run: |
  #         branch_name="${GITHUB_REF#refs/heads/}"
  #         case $branch_name in
  #           multi_tenant_*)
  #             branch_suffix=$(echo "$branch_name" | sed 's/multi_tenant_//; s/-//g')
  #             ;;
  #           mira-stage)
  #             branch_suffix="STAGE"
  #             ;;
  #           *)
  #             echo "Unsupported branch: $branch_name"
  #             exit 1
  #             ;;
  #         esac

  #         # Convert suffix to uppercase
  #         branch_suffix=$(tr '[:lower:]' '[:upper:]' <<< "$branch_suffix")
  #         echo "branch_suffix=$branch_suffix" >> $GITHUB_ENV

  #         latest_release=$(gh release list --limit 30 | grep -E "$branch_suffix" | sort -k4 -r | head -n 1 | awk '{print $1}')
  #         echo "latest_release=$latest_release" >> $GITHUB_ENV

  #         release_tag=$(gh release view $latest_release --json tagName -q ".tagName")
  #         echo "release_tag=$release_tag" >> $GITHUB_ENV

  #         commit_hash=$(gh api repos/${{ github.repository }}/git/ref/tags/$release_tag --jq '.object.sha')
  #         echo "commit_hash=$commit_hash" >> $GITHUB_ENV

  #     - name: Display Results of Release, Tag, Hash
  #       run: |
  #         echo "Branch Suffix: ${{ env.branch_suffix }}"
  #         echo "Current Release: ${{ env.latest_release }}"
  #         echo "Current Release Tag: ${{ env.release_tag }}"
  #         echo "Commit Hash of Tag: ${{ env.commit_hash }}"

  #     - name: Trigger Rollback of CodeDeploy
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #       run: |
  #         gh workflow run codedeploy-stage.yml \
  #         --ref=multi_tenant_stage \
  #         --repo prashant-cloudbolt/api \
  #         --field commit_hash=${{ env.commit_hash }} \
  #         --field codedeploy_rollback="True"

  # release_api_stage:
  #   if: ${{ github.ref == 'refs/heads/multi_tenant_stage' && always() && needs.qa-tests.result == 'success' }}  # Runs if `qa-tests` succeeds and branch is `multi_tenant_stage`
  #   needs: [qa-tests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: multi_tenant_stage

  #     - name: Run release-version workflow
  #       env:
  #         GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
  #       run: |
  #         gh workflow run release-version.yml \
  #         --ref=multi_tenant_stage \
  #         --repo prashant-cloudbolt/api