name: release-node-api-version
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo $branch_name
