name: release-dependent-version

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: string
      distinct_id:
        description: "This input required to run the workflow from return-dispatch"

jobs:
  trigger-release-version-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - node-api

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Run ${{ matrix.repository }} release version workflow of ${{ inputs.environment }}
        if: ${{ inputs.environment == 'CSMP_Stage' }}
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: multi_tenant_stage
          repo: ${{ matrix.repository }}
          owner: prashant-cloudbolt
          workflow: release-version.yml

      - name: Run ${{ matrix.repository }} release version workflow of ${{ inputs.environment }}
        if: ${{ inputs.environment == 'CSMP_Dev' }}
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: multi_tenant_dev
          repo: ${{ matrix.repository }}
          owner: prashant-cloudbolt
          workflow: release-version.yml

      - name: Watch ${{ matrix.repository }} release version workflow
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RUN_ID=${{steps.return_dispatch.outputs.run_id}}
          gh run watch $RUN_ID --repo prashant-cloudbolt/${{ matrix.repository }}

      - name: Notify failure to Slack
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() }} # This ensures the step runs only if the previous steps fail
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }} 
        with:
          status: ${{ job.status }}
          message: |
            :rotating_light: *Urgent*: Release Dependent Version Workflow Failed for API :rotating_light:
            Repository: ${{ github.repository }}
            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}