name: Upload feature_flag.json to S3 with versioning

on: 
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy the stack to.'
        default: ''
        required: false
        type: string
      feature-flag-s3-bucket:
        description: 'S3 bucket name for storing feature_flag.json file'
        default: ''
        required: true
        type: string
      feature-flag-file-name:
        description: 'File name of feature flag'
        default: ''
        required: true
        type: string
      stack-name:
        description: 'Name of the CloudFormation stack.'
        default: ''
        required: false
        type: string
      working-directory:
        description: 'The working directory to run the action in.'
        default: ''
        required: false
        type: string

permissions:
  id-token: write
  contents: read
  deployments: write

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  environment: ${{ inputs.environment }}
  s3_bucket: ${{ inputs.feature-flag-s3-bucket }}
  file_name: ${{ inputs.feature-flag-file-name }}

jobs:
  s3-feature-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the last 2 commits for comparison

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_KEY }}
          aws-region: us-east-1

      - name: Check if S3 bucket exists
        id: check-bucket
        run: |
          BUCKET_NAME=${{ env.s3_bucket }}
          echo "Checking for bucket: $BUCKET_NAME"
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "bucket_exists=true" >> $GITHUB_OUTPUT
          else
            echo "bucket_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy S3 bucket for feature flag Template
        if: steps.check-bucket.outputs.bucket_exists == 'false'
        working-directory: ${{ inputs.working-directory }}
        run: |
          aws cloudformation deploy \
            --template-file s3-feature-flag-template.yaml \
            --stack-name ${{ inputs.stack-name }} \
            --parameter-overrides \
              Environment=${{ env.environment }} \
              S3Bucket=${{ env.s3_bucket }}

      - name: Check if feature_flag.json has been modified
        id: check-modified
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD | grep -q ${{ env.file_name }}; then
            echo "featureflag_modified=true" >> $GITHUB_ENV
          else
            echo "featureflag_modified=false" >> $GITHUB_ENV
          fi

      - name: Output feature flag modified
        run: |
          echo "Feature flag modified: ${{ env.featureflag_modified }}"

      - name: Upload new feature_flag.json to S3 with versioning
        if: env.featureflag_modified == 'true'
        run: |
          aws s3 cp services/feature_flag/${{ env.file_name }} s3://${{ env.s3_bucket }}/${{ env.file_name }}